version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  email:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  postgres_data:
  redis_data: