version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - compose.env
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  email:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  postgres_data:
